### ISSUE TITLE
Not able to login via whatsapp

### ISSUE THREAD

**Issue by Afrintaj** [otpless-tech/otpless-flutter-plugin#12]
Please update Readme file with proper instructions.
https://github.com/otpless-tech/otpless-flutter-plugin/blob/master/www.otpless.com , this link is not found.
Package Example app is working fine, if we try with same code with new flutter app then _otplessFlutterPlugin.start((result) {}); not working.
not even entering inside start(); method.

**also it is asking BLUETOOTH permission**
I/InputMethodManager(24038): startInputInner - mService.startInputOrWindowGainedFocus   
W/cr_media(24038): BLUETOOTH_CONNECT permission is missing.
W/cr_media(24038): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission 

**some entry not found issue**
Unable to open '/data/app/~~5B4Gp47sXnPf77lgHmNGZQ==/com.google.android.trichromelibrary_573513033-HMslhDObZ62m7gbe0E58OA==/base.dm': No such file or directory
W/ziparchive(24038): Unable to open '/data/app/~~5B4Gp47sXnPf77lgHmNGZQ==/com.google.android.trichromelibrary_573513033-HMslhDObZ62m7gbe0E58OA==/base.dm': No such file or directory
W/le.otpless_dem(24038): Entry not found

**Comment by devbathaniotpless** [comment]
Hey @Afrintaj 
Please check our new documentation 
https://otpless.com/docs/frontend-sdks/app-sdks/flutter/headless
