### ISSUE TITLE
Images shown in document aren't showing up in the pub.dev platform.

### ISSUE THREAD

**Issue by krishnamadugu** [otpless-tech/otpless-flutter-plugin#4]
this may confuse the package users 

<img width="659" alt="Screenshot 2023-01-14 115800" src="https://user-images.githubusercontent.com/76025302/212459172-68d2c5f9-dfcd-49a1-8b02-29c26b5c5b6a.png">

**Comment by devbathaniotpless** [comment]
Hey please check our latest docs : https://otpless.com/docs/frontend-sdks/app-sdks/flutter/headless
