### ISSUE TITLE
Whatsapp not installed from api in result. (Version 1.0.9)

### ISSUE THREAD

**Issue by ps6067966** [otpless-tech/otpless-flutter-plugin#6]
![image](https://github.com/otpless-tech/otpless-flutter-plugin/assets/26248740/14cd3f1b-a452-4505-a116-53df79ff26aa)

**Comment by devbathaniotpless** [comment]
Hey @ps6067966 
Please update to latest version of otpless_flutter: 2.1.8
In initState please add a function -> //Add this code to check if whatsapp is installed on device our not
    _otplessFlutterPlugin.isWhatsAppInstalled().then((value) {
      isWhatsAppInstalled = value;
    });
    
    Please check our latest code : https://otpless.com/docs/frontend-sdks/app-sdks/flutter/headless
