### ISSUE TITLE
Downgrade plugin to work with flutter 2.10.x version

### ISSUE THREAD

**Issue by venkat-jg-github** [otpless-tech/otpless-flutter-plugin#7]
i have already made changes to make it work with flutter 2.10.x Please include recent 3 commits and release it in pub.dev

recent 3 commits from below repo :
https://github.com/venkat-jg-github/otpless_flutter/commits/master

**Comment by devbathaniotpless** [comment]
Hey @venkat-jg-github 
Please your otpless_flutter to the latest version -> 2.1.8 
Here are the new docs to integrate : https://otpless.com/docs/frontend-sdks/app-sdks/flutter/headless
