### ISSUE TITLE
Support for latest version of flutter. 3.10.5.  It is better to put constraint to 4.0.0 like all other plugins. Because of this constraint I'm not able to upgrade to latest version of otpless.

### ISSUE THREAD

**Issue by ps6067966** [otpless-tech/otpless-flutter-plugin#9]

**Comment by devbathaniotpless** [comment]
Hey @ps6067966 
Please update your otpless_flutter package to 2.1.8 version which is compatible with latest flutter, android and ios versions
Here are the new docs: https://otpless.com/docs/frontend-sdks/app-sdks/flutter/headless
